version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: compile
          command: npx tsc
      - run:
          name: test
          command: npm test

workflows:
  version: 2
  test:
    jobs:
      - test
